require('plugins')
require('plugins/nvim-treesitter')
require('plugins/neovim-ayu')
require('plugins/lualine')
require('plugins/indentLine')
require('plugins/nvim-tree')
require('plugins/nvim-cmp')
require('plugins/lspconfig')

require('options')
require('keymaps')
